export type BeneficiaryCategory =
  'nna' | 'nnaIndirect' | 'youth' | 'families' | 'teachers' | 'otherAdults' | 'institutions';

export type Project = {
  slug: string;
  name: string;
  territory: string;
  intensity: 'alta' | 'media' | 'baja';
  startYear: number;
  summary: string;
  beneficiaries: Record<BeneficiaryCategory, number>;
};

export const BENEFICIARY_CATEGORIES: {
  key: BeneficiaryCategory;
  label: string;
  definition: string;
}[] = [
  {
    key: 'nna',
    label: 'NNA',
    definition:
      'Niñas, niños y adolescentes que se benefician de forma directa del acompañamiento y de las acciones socioeducativas, promocionales o de asistencia social de un equipo técnico.',
  },
  {
    key: 'nnaIndirect',
    label: 'NNA indirectos',
    definition:
      'Niñas, niños y adolescentes alcanzados a través de otra persona o institución que sí recibe acciones del equipo técnico.',
  },
  {
    key: 'youth',
    label: 'Jóvenes',
    definition:
      'Personas de 18 a 29 años que se benefician de forma directa de alguna de las acciones.',
  },
  {
    key: 'families',
    label: 'Familias',
    definition:
      'Conjunto de individuos unidos por vínculos filiales que se benefician de forma directa de alguna de las acciones.',
  },
  {
    key: 'teachers',
    label: 'Docentes y educadores',
    definition:
      'Funcionarios de servicios básicos para las infancias —docentes, policías, personal de salud, educación no formal y programas sociales— que participan de instancias de formación.',
  },
  {
    key: 'otherAdults',
    label: 'Referentes y vecinos',
    definition:
      'Personas que reciben de forma directa acciones de sensibilización, prevención y promoción.',
  },
  {
    key: 'institutions',
    label: 'Instituciones',
    definition:
      'Referentes de instituciones con las que la organización coordina acciones de promoción de derechos.',
  },
];

export const PROJECTS: Project[] = [
  {
    slug: 'el-resorte',
    name: 'El Resorte',
    territory: 'Montevideo — Casavalle',
    intensity: 'alta',
    startYear: 2004,
    summary:
      'Centro de referencia barrial: acompañamiento educativo y trabajo con familias en Casavalle.',
    beneficiaries: {
      nna: 595,
      nnaIndirect: 184,
      youth: 63,
      families: 88,
      teachers: 99,
      otherAdults: 66,
      institutions: 10,
    },
  },
  {
    slug: 'revuelos',
    name: 'Revuelos',
    territory: 'Montevideo — Cerro',
    intensity: 'alta',
    startYear: 2011,
    summary: 'Espacio socioeducativo para adolescentes que sostienen su trayectoria liceal.',
    beneficiaries: {
      nna: 486,
      nnaIndirect: 150,
      youth: 51,
      families: 72,
      teachers: 81,
      otherAdults: 54,
      institutions: 9,
    },
  },
  {
    slug: 'molinillo',
    name: 'Molinillo',
    territory: 'Canelones',
    intensity: 'alta',
    startYear: 2016,
    summary: 'Primera infancia y crianza: talleres con familias y articulación con CAIF.',
    beneficiaries: {
      nna: 549,
      nnaIndirect: 170,
      youth: 58,
      families: 81,
      teachers: 91,
      otherAdults: 61,
      institutions: 10,
    },
  },
  {
    slug: 'cnpi-bitacoras',
    name: 'CNPI — Bitácoras',
    territory: 'Nacional',
    intensity: 'media',
    startYear: 2019,
    summary: 'Sistematización de prácticas de promoción de derechos junto al Comité Nacional.',
    beneficiaries: {
      nna: 267,
      nnaIndirect: 157,
      youth: 72,
      families: 28,
      teachers: 255,
      otherAdults: 42,
      institutions: 12,
    },
  },
  {
    slug: 'marcando-la-cancha',
    name: 'Marcando la Cancha',
    territory: 'Montevideo — Casavalle',
    intensity: 'media',
    startYear: 2021,
    summary: 'Deporte como puerta de entrada: fútbol, convivencia y derechos. Con Fundación FIFA.',
    beneficiaries: {
      nna: 240,
      nnaIndirect: 141,
      youth: 65,
      families: 26,
      teachers: 229,
      otherAdults: 38,
      institutions: 11,
    },
  },
  {
    slug: 'apoyando-trayectorias-educativas',
    name: 'Apoyando Trayectorias Educativas',
    territory: 'Montevideo',
    intensity: 'alta',
    startYear: 2018,
    summary: 'Tutorías y becas para revertir el desvínculo escolar en el ciclo básico.',
    beneficiaries: {
      nna: 577,
      nnaIndirect: 178,
      youth: 61,
      families: 85,
      teachers: 96,
      otherAdults: 64,
      institutions: 10,
    },
  },
  {
    slug: 'centro-juvenil',
    name: 'Centro Juvenil',
    territory: 'Montevideo — Cerro',
    intensity: 'alta',
    startYear: 2009,
    summary: 'Centro juvenil de tiempo completo: talleres, egreso y orientación laboral.',
    beneficiaries: {
      nna: 648,
      nnaIndirect: 200,
      youth: 68,
      families: 96,
      teachers: 108,
      otherAdults: 71,
      institutions: 11,
    },
  },
  {
    slug: 'en-ruta',
    name: 'En Ruta',
    territory: 'Salto',
    intensity: 'media',
    startYear: 2020,
    summary: 'Acompañamiento a adolescentes en situación de calle y a sus referentes.',
    beneficiaries: {
      nna: 182,
      nnaIndirect: 107,
      youth: 48,
      families: 19,
      teachers: 175,
      otherAdults: 28,
      institutions: 7,
    },
  },
  {
    slug: 'guia-vshnna',
    name: 'Guía VSHNNA',
    territory: 'Nacional',
    intensity: 'baja',
    startYear: 2022,
    summary:
      'Guía de actuación frente a violencia sexual hacia NNA, con el Ministerio del Interior.',
    beneficiaries: {
      nna: 17,
      nnaIndirect: 54,
      youth: 7,
      families: 1,
      teachers: 157,
      otherAdults: 17,
      institutions: 4,
    },
  },
  {
    slug: 'capacitacion-ciemsa',
    name: 'Capacitación CIEMSA',
    territory: 'Nacional',
    intensity: 'baja',
    startYear: 2023,
    summary: 'Formación a funcionarios del sistema educativo medio en enfoque de derechos.',
    beneficiaries: {
      nna: 15,
      nnaIndirect: 47,
      youth: 6,
      families: 1,
      teachers: 137,
      otherAdults: 15,
      institutions: 4,
    },
  },
  {
    slug: 'habilidades-digitales',
    name: 'Habilidades Digitales',
    territory: 'Paysandú',
    intensity: 'media',
    startYear: 2022,
    summary: 'Alfabetización digital para jóvenes que buscan su primer empleo. Con Inefop.',
    beneficiaries: {
      nna: 236,
      nnaIndirect: 139,
      youth: 64,
      families: 25,
      teachers: 226,
      otherAdults: 36,
      institutions: 10,
    },
  },
  {
    slug: 'despegue-digital',
    name: 'Despegue Digital',
    territory: 'Rivera',
    intensity: 'media',
    startYear: 2023,
    summary: 'Segunda edición del programa digital, ampliada al norte del país. Con Inefop.',
    beneficiaries: {
      nna: 244,
      nnaIndirect: 144,
      youth: 66,
      families: 26,
      teachers: 234,
      otherAdults: 39,
      institutions: 11,
    },
  },
  {
    slug: 'activate',
    name: 'Activate',
    territory: 'Montevideo',
    intensity: 'media',
    startYear: 2021,
    summary: 'Participación juvenil: los jóvenes diseñan y ejecutan proyectos en su barrio.',
    beneficiaries: {
      nna: 241,
      nnaIndirect: 142,
      youth: 65,
      families: 26,
      teachers: 231,
      otherAdults: 38,
      institutions: 11,
    },
  },
  {
    slug: 'formacion-eti',
    name: 'Formación ETI',
    territory: 'Nacional',
    intensity: 'baja',
    startYear: 2020,
    summary: 'Formación a equipos técnicos sobre explotación y trata de NNA.',
    beneficiaries: {
      nna: 15,
      nnaIndirect: 47,
      youth: 6,
      families: 1,
      teachers: 138,
      otherAdults: 15,
      institutions: 4,
    },
  },
  {
    slug: 'aula-tecnologica-eti',
    name: 'Aula Tecnológica ETI',
    territory: 'Montevideo',
    intensity: 'baja',
    startYear: 2021,
    summary: 'Aula equipada para talleres de prevención con adolescentes.',
    beneficiaries: {
      nna: 23,
      nnaIndirect: 71,
      youth: 9,
      families: 2,
      teachers: 209,
      otherAdults: 22,
      institutions: 6,
    },
  },
  {
    slug: 'ceibal-pc',
    name: 'Ceibal-pc',
    territory: 'Nacional',
    intensity: 'media',
    startYear: 2019,
    summary: 'Entrega y soporte de equipamiento junto a Plan Ceibal.',
    beneficiaries: {
      nna: 261,
      nnaIndirect: 153,
      youth: 70,
      families: 28,
      teachers: 250,
      otherAdults: 41,
      institutions: 11,
    },
  },
  {
    slug: 'aula-digital-mig',
    name: 'Aula Digital MIG',
    territory: 'Montevideo',
    intensity: 'baja',
    startYear: 2022,
    summary: 'Aula digital en el marco del Modelo de Inclusión Garantizada.',
    beneficiaries: {
      nna: 24,
      nnaIndirect: 76,
      youth: 10,
      families: 2,
      teachers: 223,
      otherAdults: 24,
      institutions: 6,
    },
  },
  {
    slug: 'steam-club-de-ninos',
    name: 'STEAM — Club de Niños',
    territory: 'Canelones',
    intensity: 'media',
    startYear: 2022,
    summary: 'Ciencia y tecnología con enfoque de género en clubes de niños.',
    beneficiaries: {
      nna: 184,
      nnaIndirect: 108,
      youth: 50,
      families: 19,
      teachers: 177,
      otherAdults: 28,
      institutions: 8,
    },
  },
  {
    slug: 'somos-equidad',
    name: 'Somos Equidad',
    territory: 'Nacional',
    intensity: 'media',
    startYear: 2020,
    summary: 'Masculinidades y equidad de género con adolescentes y docentes.',
    beneficiaries: {
      nna: 167,
      nnaIndirect: 98,
      youth: 44,
      families: 17,
      teachers: 159,
      otherAdults: 26,
      institutions: 7,
    },
  },
  {
    slug: 'unfpa-msp',
    name: 'UNFPA — MSP',
    territory: 'Nacional',
    intensity: 'baja',
    startYear: 2023,
    summary: 'Salud sexual y reproductiva adolescente junto a UNFPA y el MSP.',
    beneficiaries: {
      nna: 18,
      nnaIndirect: 55,
      youth: 7,
      families: 1,
      teachers: 161,
      otherAdults: 17,
      institutions: 5,
    },
  },
  {
    slug: 'metejon',
    name: 'MetejON',
    territory: 'Montevideo — Casavalle',
    intensity: 'alta',
    startYear: 2017,
    summary: 'Fútbol infantil y trabajo con familias: la cancha como espacio de derechos.',
    beneficiaries: {
      nna: 409,
      nnaIndirect: 126,
      youth: 42,
      families: 61,
      teachers: 68,
      otherAdults: 45,
      institutions: 6,
    },
  },
  {
    slug: 'ru-bienestar-socioemocional',
    name: 'RU Bienestar Socioemocional',
    territory: 'Tacuarembó',
    intensity: 'media',
    startYear: 2021,
    summary: 'Convivencia y bienestar socioemocional en centros educativos rurales.',
    beneficiaries: {
      nna: 201,
      nnaIndirect: 117,
      youth: 54,
      families: 21,
      teachers: 192,
      otherAdults: 31,
      institutions: 9,
    },
  },
  {
    slug: 'upm-habilidades-socioemocionales',
    name: 'UPM Habilidades Socioemocionales',
    territory: 'Paysandú',
    intensity: 'media',
    startYear: 2022,
    summary: 'Habilidades socioemocionales en escuelas de la zona de influencia de UPM.',
    beneficiaries: {
      nna: 204,
      nnaIndirect: 120,
      youth: 55,
      families: 22,
      teachers: 195,
      otherAdults: 31,
      institutions: 9,
    },
  },
  {
    slug: 'mesas-barriales',
    name: 'Mesas Barriales',
    territory: 'Montevideo',
    intensity: 'media',
    startYear: 2015,
    summary: 'Articulación comunitaria: vecinos e instituciones en la misma mesa.',
    beneficiaries: {
      nna: 161,
      nnaIndirect: 94,
      youth: 43,
      families: 17,
      teachers: 154,
      otherAdults: 25,
      institutions: 6,
    },
  },
  {
    slug: 'poli-ball',
    name: 'Poli Ball',
    territory: 'Canelones',
    intensity: 'media',
    startYear: 2023,
    summary: 'Deporte y vínculo con la policía comunitaria. Con Unicef.',
    beneficiaries: {
      nna: 160,
      nnaIndirect: 94,
      youth: 43,
      families: 16,
      teachers: 153,
      otherAdults: 25,
      institutions: 6,
    },
  },
  {
    slug: 'cuidarte-esta-en-juego',
    name: 'Cuidarte Está en Juego',
    territory: 'Nacional',
    intensity: 'baja',
    startYear: 2024,
    summary: 'Prevención del abuso a través del juego, en centros de primera infancia.',
    beneficiaries: {
      nna: 14,
      nnaIndirect: 44,
      youth: 6,
      families: 1,
      teachers: 129,
      otherAdults: 14,
      institutions: 4,
    },
  },
  {
    slug: 'yo-estudio-y-trabajo',
    name: 'Yo Estudio y Trabajo',
    territory: 'Nacional',
    intensity: 'media',
    startYear: 2019,
    summary: 'Primera experiencia laboral formal para estudiantes de 16 a 20 años.',
    beneficiaries: {
      nna: 177,
      nnaIndirect: 104,
      youth: 47,
      families: 18,
      teachers: 171,
      otherAdults: 27,
      institutions: 7,
    },
  },
];

export const ANNUAL_REACH = [
  { year: 2019, reach: 7117 },
  { year: 2020, reach: 8273 },
  { year: 2021, reach: 10533 },
  { year: 2022, reach: 12593 },
  { year: 2023, reach: 14878 },
  { year: 2024, reach: 16192 },
  { year: 2025, reach: 17067 },
];

export function getTotals() {
  return BENEFICIARY_CATEGORIES.map((category) => ({
    ...category,
    total: PROJECTS.reduce((sum, project) => sum + project.beneficiaries[category.key], 0),
  }));
}

export function getProjectReach(project: Project) {
  return BENEFICIARY_CATEGORIES.reduce(
    (sum, category) => sum + project.beneficiaries[category.key],
    0
  );
}
